### ISSUE TITLE
Add logic for identical functions

### ISSUE THREAD

**Issue by nouranAbdelhady** [randarihany/notification#1]
`public void AddAssignment(String assignName, String assignBody) {
		announcements.add(assignName);
		String[] placeholders = new String[] {assignName, assignBody};
		// do some logic here 
		
		notifyAllUsers(placeholders);
	}
	public void AddExam(String assignName, String assignBody) {
		announcements.add(assignName);
		String[] placeholders = new String[] {assignName, assignBody};
		// do some logic here

		notifyAllUsers(placeholders);
	}

	public void PostGrades(String assignName, String assignBody) {
		announcements.add(assignName);
		String[] placeholders = new String[] {assignName, assignBody};
		// do some logic here

		notifyAllUsers(placeholders);
	}
`

**Comment by randarihany** [comment]
logic will be at later phase
